services:
  client:
    build:
      context: .
      dockerfile: compareWebClient.Dockerfile
    ports:
      - "7012:80"
  api:
    build:
      context: .
      dockerfile: compareWebApi.Dockerfile
    ports:
      - "7011:80"
    volumes:
      - ./data_directory:/data_directory
      - ./refseq_databases:/fasta_files
      - ./compare_web:/app
    depends_on:
      - rabbit
      - celeryworker
  rabbit:
    image: 'rabbitmq'
    ports:
      - "7672:5672"
  celeryworker:
    build:
      context: .
      dockerfile: compareWebWorker.Dockerfile
    volumes:
      - ./data_directory:/data_directory
      - ./refseq_databases:/fasta_files
    platform: linux/x86_64
    depends_on:
      - rabbit
    deploy:
      mode: replicated
      replicas: 2

